### ISSUE TITLE
Extension not working on onprem TFS 2015 Update 2.1

### ISSUE THREAD

**Issue by lealcrf** [areve/IframeDashboardWidget#3]
The extension just doesn't show as an available extension, even after a sucessfull installation.

**Comment by areve** [comment]
I don't have onprem TFS 2015 to try this on. I know the extension is working for other TFS users though but can't help solve this. 

I've tested that the widget is still working today on a VSTS site.

If you do manage to work out how to fix don't hesitate in submitting a patch.

**Comment by jmezach** [comment]
The problem with this is that although you can install a dashboard widget extension into TFS 2015 Update 2.1 they aren't actually supported until TFS 2015 Update 3. So you'll have to update your TFS server to Update 3 to get this to work.

**Comment by jnhaffey** [comment]
Sadly I just installed it on a TFS 2015 Update 3 and while it installed, the Widget does not show up as an available item to add to a dashboard.  This idea is key to a new direction my team is going so I will (myself and another team member) will see if we can figure out why its not working.

**Comment by jnhaffey** [comment]
We may have found the issue.  Our TFS Server is throwing the following Exception Message: This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet. (type InvalidOperationException)

We are going to try turning your 'GET' to a 'POST' which should hopefully fix the issue.

**Comment by jnhaffey** [comment]
Right I would like to retract my prevent comments, I thought my TFS was running Update 3 but turns out it was actually running Update 2.  I installed the TFS Update 3 this past weekend and re-installed your iFrame Add-On.  Works!
